import { NotificationChannel } from '../generated/prisma/index.js';
import { prisma } from '../prisma/client.js';

const templates = [
  {
    code: 'asset-created-inapp',
    name: 'Asset Created In-App',
    channel: NotificationChannel.InApp,
    subject: 'New extinguisher registered',
    body: 'Fire extinguisher {{assetCode}} has been registered. Expires on {{expirationDate}}.',
    eventType: 'AssetCreated',
  },
  {
    code: 'asset-expiring-email',
    name: 'Asset Expiring Soon Email',
    channel: NotificationChannel.Email,
    subject: 'Extinguisher {{assetCode}} expiring soon',
    body: 'Your fire extinguisher {{assetCode}} expires on {{expirationDate}}. Please schedule inspection or replacement.',
    eventType: 'AssetExpiringSoon',
  },
  {
    code: 'asset-expiring-inapp',
    name: 'Asset Expiring Soon In-App',
    channel: NotificationChannel.InApp,
    subject: 'Extinguisher expiring soon',
    body: 'Extinguisher {{assetCode}} expires on {{expirationDate}}.',
    eventType: 'AssetExpiringSoon',
  },
  {
    code: 'asset-expired-email',
    name: 'Asset Expired Email',
    channel: NotificationChannel.Email,
    subject: 'URGENT: Extinguisher {{assetCode}} has expired',
    body: 'Your fire extinguisher {{assetCode}} expired on {{expirationDate}}. Replace or service it immediately to stay compliant.',
    eventType: 'AssetExpired',
  },
  {
    code: 'asset-expired-inapp',
    name: 'Asset Expired In-App',
    channel: NotificationChannel.InApp,
    subject: 'Extinguisher expired',
    body: 'Extinguisher {{assetCode}} has expired. Immediate action required.',
    eventType: 'AssetExpired',
  },
  {
    code: 'expiry-reminder-email',
    name: 'Expiry Reminder Email',
    channel: NotificationChannel.Email,
    subject: '{{alertSubject}}',
    body: '{{alertBody}}',
    eventType: 'ExpiryReminder',
  },
  {
    code: 'expiry-reminder-inapp',
    name: 'Expiry Reminder In-App',
    channel: NotificationChannel.InApp,
    subject: '{{alertSubject}}',
    body: '{{alertBody}}',
    eventType: 'ExpiryReminder',
  },
  {
    code: 'expiry-30-days',
    name: 'Expiry 30-Day Reminder',
    channel: NotificationChannel.Email,
    subject: 'Extinguisher {{assetCode}} expires in 30 days',
    body: 'Reminder: Your fire extinguisher {{assetCode}} will expire on {{expirationDate}} (about 30 days remaining).',
    eventType: 'ExpiryAlert30',
  },
  {
    code: 'expiry-30-days-inapp',
    name: 'Expiry 30-Day In-App',
    channel: NotificationChannel.InApp,
    subject: '30-day expiry reminder',
    body: 'Extinguisher {{assetCode}} expires on {{expirationDate}}.',
    eventType: 'ExpiryAlert30',
  },
  {
    code: 'expiry-7-days',
    name: 'Expiry 7-Day Reminder',
    channel: NotificationChannel.Email,
    subject: 'Extinguisher {{assetCode}} expires in 7 days',
    body: 'Your fire extinguisher {{assetCode}} expires on {{expirationDate}} (7 days remaining). Please act soon.',
    eventType: 'ExpiryAlert7',
  },
  {
    code: 'expiry-7-days-inapp',
    name: 'Expiry 7-Day In-App',
    channel: NotificationChannel.InApp,
    subject: '7-day expiry reminder',
    body: 'Extinguisher {{assetCode}} expires in 7 days ({{expirationDate}}).',
    eventType: 'ExpiryAlert7',
  },
  {
    code: 'expiry-on-date',
    name: 'Expiry On Date Email',
    channel: NotificationChannel.Email,
    subject: 'Extinguisher {{assetCode}} expires today',
    body: 'Your fire extinguisher {{assetCode}} expires today ({{expirationDate}}). Arrange replacement or service immediately.',
    eventType: 'ExpiryAlertOnDate',
  },
  {
    code: 'expiry-on-date-inapp',
    name: 'Expiry On Date In-App',
    channel: NotificationChannel.InApp,
    subject: 'Extinguisher expires today',
    body: 'Extinguisher {{assetCode}} expires today. Please arrange replacement or service.',
    eventType: 'ExpiryAlertOnDate',
  },
  {
    code: 'expiry-overdue',
    name: 'Expiry Overdue Email',
    channel: NotificationChannel.Email,
    subject: 'OVERDUE: Extinguisher {{assetCode}}',
    body: 'Your fire extinguisher {{assetCode}} expired on {{expirationDate}} and is now overdue. Compliance action is required.',
    eventType: 'ExpiryAlertOverdue',
  },
  {
    code: 'expiry-overdue-inapp',
    name: 'Expiry Overdue In-App',
    channel: NotificationChannel.InApp,
    subject: 'Extinguisher overdue',
    body: 'Extinguisher {{assetCode}} is overdue since {{expirationDate}}.',
    eventType: 'ExpiryAlertOverdue',
  },
  {
    code: 'service-completed-email',
    name: 'Service Completed Email',
    channel: NotificationChannel.Email,
    subject: 'Maintenance completed — {{requestNumber}}',
    body: 'Your maintenance request {{requestNumber}} ({{type}}) has been completed.',
    eventType: 'ServiceCompleted',
  },
  {
    code: 'service-completed-inapp',
    name: 'Service Completed In-App',
    channel: NotificationChannel.InApp,
    subject: 'Maintenance completed',
    body: 'Request {{requestNumber}} is now complete.',
    eventType: 'ServiceCompleted',
  },
  {
    code: 'service-request-created-inapp',
    name: 'Service Request Created In-App',
    channel: NotificationChannel.InApp,
    subject: 'Maintenance request received',
    body: 'Your request {{requestNumber}} ({{type}}) was submitted and is pending assignment.',
    eventType: 'ServiceRequested',
  },
  {
    code: 'service-request-created-email',
    name: 'Service Request Created Email',
    channel: NotificationChannel.Email,
    subject: 'Maintenance request {{requestNumber}} received',
    body: 'We received your maintenance request {{requestNumber}} for {{type}}. You will be notified when an inspector is assigned.',
    eventType: 'ServiceRequested',
  },
  {
    code: 'inspector-assigned-user-inapp',
    name: 'Inspector Assigned User In-App',
    channel: NotificationChannel.InApp,
    subject: 'Inspector assigned',
    body: '{{technicianName}} has been assigned to your request {{requestNumber}}.',
    eventType: 'TechnicianAssigned',
  },
  {
    code: 'inspector-assigned-user-email',
    name: 'Inspector Assigned User Email',
    channel: NotificationChannel.Email,
    subject: 'Inspector assigned to {{requestNumber}}',
    body: '{{technicianName}} will handle your {{type}} request {{requestNumber}}.',
    eventType: 'TechnicianAssigned',
  },
  {
    code: 'inspector-assigned-inspector-inapp',
    name: 'Inspector Assigned Inspector In-App',
    channel: NotificationChannel.InApp,
    subject: 'New assignment',
    body: 'You were assigned maintenance request {{requestNumber}} ({{type}}).',
    eventType: 'TechnicianAssigned',
  },
  {
    code: 'inspector-assigned-inspector-email',
    name: 'Inspector Assigned Inspector Email',
    channel: NotificationChannel.Email,
    subject: 'Assigned: {{requestNumber}}',
    body: 'You have been assigned to maintenance request {{requestNumber}} ({{type}}). Log in to review and update progress.',
    eventType: 'TechnicianAssigned',
  },
  {
    code: 'service-status-inapp',
    name: 'Service Status In-App',
    channel: NotificationChannel.InApp,
    subject: 'Request {{requestNumber}} updated',
    body: 'Status is now {{newStatus}}.',
    eventType: 'ServiceStatusChanged',
  },
  {
    code: 'maintenance-due-email',
    name: 'Maintenance Due Email',
    channel: NotificationChannel.Email,
    subject: 'Maintenance due — {{assetCode}}',
    body: 'Extinguisher {{assetCode}} is due for service on {{nextServiceDate}} ({{daysUntilService}} days remaining).',
    eventType: 'MAINTENANCE_REMINDER',
  },
  {
    code: 'maintenance-due-inapp',
    name: 'Maintenance Due In-App',
    channel: NotificationChannel.InApp,
    subject: 'Maintenance due — {{assetCode}}',
    body: 'Extinguisher {{assetCode}} is due for service on {{nextServiceDate}}.',
    eventType: 'MAINTENANCE_REMINDER',
  },
  {
    code: 'maintenance-overdue-email',
    name: 'Maintenance Overdue Email',
    channel: NotificationChannel.Email,
    subject: 'Maintenance overdue — {{assetCode}}',
    body: 'Extinguisher {{assetCode}} is {{daysOverdue}} day(s) past due service (was due {{nextServiceDate}}).',
    eventType: 'MAINTENANCE_REMINDER',
  },
  {
    code: 'maintenance-overdue-inapp',
    name: 'Maintenance Overdue In-App',
    channel: NotificationChannel.InApp,
    subject: 'Maintenance overdue — {{assetCode}}',
    body: 'Extinguisher {{assetCode}} is {{daysOverdue}} day(s) overdue for service.',
    eventType: 'MAINTENANCE_REMINDER',
  },
  {
    code: 'inspection-overdue-inapp',
    name: 'Inspection Overdue In-App',
    channel: NotificationChannel.InApp,
    subject: 'Inspection overdue — {{requestNumber}}',
    body: 'Service request {{requestNumber}} is {{daysOverdue}} day(s) past its scheduled inspection date.',
    eventType: 'INSPECTION_OVERDUE',
  },
];

export async function bootstrapNotificationTemplates(): Promise<void> {
  for (const template of templates) {
    await prisma.notificationTemplate.upsert({
      where: { code: template.code },
      update: template,
      create: template,
    });
  }
  console.log(`[notification-service] Ensured ${templates.length} notification templates`);
}
